### DISCUSSION TITLE
What is the recommended method for proxy http api?

### DISCUSSION THREAD

**Discussion by uanid** [remix-run/remix#10545] [Q&A]
Hello,
I would like to use Remix with an already completed backend server and SDK.

I am aware that simple APIs can be proxied using Remix’s action function. However, the backend server I am using is more complex.
For example, I would like to proxy the following types of APIs:
1. HTTP GET, POST, PUT, DELETE, PATCH methods
2. Response long polling (e.g., Server-Sent Events)
3. HTTP WATCH, SEARCH methods

I know that the first case can be implemented using Remix action, but I found that the others are not possible.

Currently, in the development environment, I use the proxy settings in vite.config.ts.
```ts
        server: {
            proxy: {
                "/api": {
                    target: apiOrigin,
                    changeOrigin: true,
                },
                "/apis": {
                    target: apiOrigin,
                    changeOrigin: true,
                },
                "/versions": {
                    target: apiOrigin,
                    changeOrigin: true,
                },
            },
        },
```

In the production environment, I utilize the proxy functionality of the L7 Load Balancer. 

Like this(Istio Configuration),
```yaml
  virtualService:
      - name: "proxy-to-apiserver"
        match:
          - uri:
              prefix: "/api"
          - uri:
              prefix: "/apis"
          - uri:
              prefix: "/versions"
        route:
          - destination:
              host: airdrop-${server_stage}-apiserver
              port:
                number: 3000
              subset: default
```

Is there any better approach than this?
