### DISCUSSION TITLE
AWS Ampify + RemixJS Support

### DISCUSSION THREAD

**Discussion by andrewoodleyjr** [remix-run/remix#10588] [Q&A]
I've been working on getting two Remix.js websites up and running on AWS Ampify and have not been successful. 

Looking at the logs the application builds properly however nothing shows when visiting. 
I'm sure I'm missing something. 

I'd rather focus on building and not dev ops so before I give up and go to another framework I want to ask the community

ampify.yml
```
version: 1
frontend:
    phases:
        preBuild:
            commands:
                - 'npm ci --cache .npm --prefer-offline'
        build:
            commands:
                - 'npm run build'
    artifacts:
        baseDirectory: build
        files:
            - '**/*'
    cache:
        paths:
            - '.npm/**/*'
```

package.json
```
{
  "name": "frontend",
  "private": true,
  "sideEffects": false,
  "type": "module",
  "scripts": {
    "build": "remix vite:build",
    "dev": "remix vite:dev",
    "lint": "eslint --ignore-path .gitignore --cache --cache-location ./node_modules/.cache/eslint .",
    "start": "remix-serve ./build/server/index.js",
    "typecheck": "tsc"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^6.11.0",
    "@headlessui/react": "^2.2.1",
    "@heroicons/react": "^2.2.0",
    "@remix-run/node": "^2.16.4",
    "@remix-run/react": "^2.16.4",
    "@remix-run/serve": "^2.16.4",
    "aws-amplify": "^6.14.2",
    "devices.css": "^0.2.0",
    "isbot": "^4.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^2.16.4",
    "@types/react": "^18.3.20",
    "@types/react-dom": "^18.3.6",
    "@typescript-eslint/eslint-plugin": "^6.7.4",
    "@typescript-eslint/parser": "^6.7.4",
    "autoprefixer": "^10.4.21",
    "eslint": "^8.38.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "postcss": "^8.5.3",
    "tailwindcss": "^3.4.17",
    "typescript": "^5.1.6",
    "vite": "^6.0.0",
    "vite-tsconfig-paths": "^4.2.1"
  },
  "engines": {
    "node": ">=20.0.0"
  }
}
```
remix.config.js
```
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  serverModuleFormat: "cjs",
  future: {
    v2_dev: true,
    v2_errorBoundary: true,
    v2_headers: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
  devServerBroadcastDelay: 1000,
  assetsBuildDirectory: "public/build",
  serverBuildPath: "build/index.js",
  publicPath: "/build/",
}; 
```
