### DISCUSSION TITLE
Question about the docker-compose setup in the blues-stack

### DISCUSSION THREAD

**Discussion by amirhhashemi** [remix-run/remix#2976] [Q&A] [answered]
**I'm new to docker and web dev in general so expect a newbie question.** Here might not be the best place to ask it, because **it's more about docker than remix** but the community looks nice and I don't know a better place to ask it.

This is the `docker-compose.yml` file from the [`blues-stack`](https://github.com/remix-run/blues-stack):
```yml
version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
```
If `docker-compose` is used for local development, why there is not a `web` (or whatever) service that starts the actual application? A docker-compose file that just starts a database is weird for me. I guess I can add it myself but I want to know if there is a particular reason that's not done by default.
