### DISCUSSION TITLE
Rewrite the template to be compatible with wrangler v2

### DISCUSSION THREAD

**Discussion by aiji42** [remix-run/remix#3158] [Proposals]
https://github.com/cloudflare/wrangler2

wrangler v2 has been released. the CF Workers template in Remix is still v1 and needs to be rewritten to work with v2.
May I create a pull request?

wrangler.toml
```toml
name = "remix-cloudflare-workers"

compatibility_date = "2022-05-11"

account_id = ""
workers_dev = true
main = "./build/index.js"


[site]
bucket = "./public"

[build]
command = "npm run build"
```

package.json
```json
  "devDependencies": {
    "@cloudflare/workers-types": "^3.4.0",
    "@remix-run/dev": "*",
    "@remix-run/eslint-config": "*",
    "@types/react": "^17.0.24",
    "@types/react-dom": "^17.0.9",
    "eslint": "^8.11.0",
    "miniflare": "^2.1.0",
    "npm-run-all": "^4.1.5",
    "typescript": "^4.5.5",
    "wrangler": "^2.0.2"
  },
```
