### DISCUSSION TITLE
Is there a way to safely use Sentry's source map feature in a production environment?

### DISCUSSION THREAD

**Discussion by convcha** [remix-run/remix#4343] [Q&A] [answered]
I use Remix along with Sentry's source map support.

https://docs.sentry.io/platforms/javascript/guides/remix/

This is extremely useful!
However, I am not sure if it is safe to use this source map feature in Production.

I initially thought it would be this way.

a) Source code to upload to Sentry.
Generated with `remix build -sourcemap`.

b) Source code to actually run on the server
Generated with `remix build`.

However, the file names in a) and b) do not match in this way.

e.g.
With source map
public/build/routes/index-V3LYSNCQ.js
public/build/routes/index-V3LYSNCQ.js.map

Without source map
public/build/routes/index-H3XOOMVB.js

Therefore, you need to generate b) with `remix build -sourcemap`.
This will cause the browser to see the source code before compression, so we manually remove the .map file.
However, for some reason, the source code of `entry.client.tsx` and `root.tsx` is visible.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/3993599/194617235-aa2b8a2c-851f-496a-8ab6-bcaa0e5d5891.png">

Also, when I run `remix build -sourcemap`, I get a strong warning as shown below.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/3993599/194615542-d139e09b-1730-4f64-8635-17c15367af8f.png">

Even if you are careful not to hardcode the secret as described in this warning, it is still a bit scary....
What is the best way to do this?

https://github.com/remix-run/remix/issues/355
I thought this issue was related but I am not sure.

**Comment by sergiodxa** [comment, marked as answer]
After the build, upload the source maps to Sentry, then remove it from the public/build folder and deploy.

**Reply by convcha** [reply]
I got it.
Thanks!

**Comment by thomasverleye** [comment]
@convcha did you end up removing the source maps?
In our current setup we're experiencing issues with Sentry not recognizing the source file paths and pointing it to the build files instead when we remove our source maps 🙃

**Reply by convcha** [reply]
Yes, I am deleting the source map.
I use Fly.io and remove the source map in the Dockerfile when deploying.

Dockerfile

```
...
# Delete source maps after build
RUN rm -f ./apps/web/public/build/**/*.map
...
```

After deployment, the Sentry source map is uploaded in GitHub Actions.

GitHub Actions

```yaml
- name: Create Sentry release
  uses: getsentry/action-release@v1
  env:
    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
    SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  with:
    environment: ${{ inputs.environment }}
    ignore_empty: true
    version: ${{ env.APP_VERSION }}
```

```yaml
- name: Upload source maps to Sentry
  run: |
    pnpm build
    cd ./apps/web # I use Turborepo
    pnpm sentry-upload-sourcemaps --release ${{ env.APP_VERSION }}
  env:
    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
    SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
```
