### DISCUSSION TITLE
CSS Modules with Sass?

### DISCUSSION THREAD

**Discussion by DaveAllbirds** [remix-run/remix#5579] [Q&A]
Is it possible to use CSS Modules with Sass? I've been trying to get the following working without any luck:

```CSS
/* button.module.scss */

@import '~/styles/mediaQueries.scss';

.button {
  @include mediumUp {
    padding-top: calc(var(--spacing) * 10px);
  }
}
```

Ideally, I'm looking for CSS bundling so there aren't .css files generated in the codebase.

Thanks!
