### DISCUSSION TITLE
UI Components - CJS + require('./path/to.css')

### DISCUSSION THREAD

**Discussion by shainegordon** [remix-run/remix#7236] [Q&A]
Our CX team have created a set of React UI components that we need to use in our applications.

These components are currently being used in Gatsby and NextJS.

I am now looking to use them in Remix.

I have a minimal Remix app configured using `pnpm create remix@latest`

When I try to use a component in my route, i'll get the following error

```
d:\projects\remix-org-cx\node_modules\.pnpm\@orgcx+react-ui-next-provider@15.44.32_react@18.2.0\node_modules\@orgcx\react-ui-next-provider\dist\styles.css:1
@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap");
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (d:\projects\remix-org-cx\node_modules\.pnpm\@orgcx+react-ui-next-provider@15.44.32_react@18.2.0\node_modules\@orgcx\react-ui-next-provider\index.cjs:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
```

Here are the details of the package/component

```tsx
// routes/playground.tsx
import Provider from '@orgcx/react-ui-next-provider';

export default function Playground() {
    return (
        <Provider>
            <p>Testing component library integration
        </Provider>
    )
}
```

```js
// @orgcx/react-ui-next-provider/package.json
{
    "name": "@orgcx/react-ui-next-provider",
    "main": "./index.cjs",
    "types": "./dist/public.d.ts",
    "files": [
        "index.cjs",
        "dist"
    ],
    "style": "dist/styles.css",
}
```

```js
// @orgcx/react-ui-next-provider/index.cjs
require('./dist/styles.css');
module.exports = require('./dist/commonjs.cjs');
```

```css
// @orgcx/react-ui-next-provider/dist/styles.css
@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap");

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, menu, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
main, menu, nav, output, ruby, section, summary,
time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline;
}
//snipped
```

I think I understand why this is happening -> the node CJS loader has no idea how to load/parse CSS.

What I dont know is how I can go about fixing this
