### DISCUSSION TITLE
Fly.io deploy directions

### DISCUSSION THREAD

**Discussion by quangv** [remix-run/remix#7569] [General]
Took me a bit to actually deploy the app (hello world) onto the interwebs. This was how I was able to finally see it.

```sh
fly ips allocate-v6  # not sure if this is necessary
fly ips allocate-v4 --shared
```

manually create a `fly.toml` file:

```toml
app = "XXX"
primary_region = "XXX"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
```

With the above, `npm run deploy` actually exposes the app and was able to see it with command `fly apps open` (opens the app in my browser)
