### DISCUSSION TITLE
How to load font asset on loader

### DISCUSSION THREAD

**Discussion by jacargentina** [remix-run/remix#9273] [Q&A]
My example app is here

https://github.com/jacargentina/my-remix-app

I'm trying to load a TTF font, to render a PDF later; I'm struggling to make it work on Vercel, as the TTF is not being put on the server assets.

Any advice would be very appreciated!

**Comment by suhaotian** [comment]
Put the font to public folder, then use CSS font-face to load the font:

```css
@font-face {
  font-family: 'MyWebFont';
  src: url('webfont.eot'); /* IE9 Compat Modes */
  src: url('webfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('webfont.woff2') format('woff2'), /* Super Modern Browsers */
       url('webfont.woff') format('woff'), /* Pretty Modern Browsers */
       url('webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('webfont.svg#svgFontName') format('svg'); /* Legacy iOS */
}
```
