### ISSUE TITLE
Unexpected Token Error with @layer Directive in PostCSS with Remix and Shadcn

### ISSUE THREAD

**Issue by maruf-pfc** [remix-run/remix#10292]
### Reproduction

I am encountering a persistent issue when using the @layer directive in my CSS with PostCSS while working on a Remix project that utilizes Shadcn. The error message I receive is as follows:

```txt
[plugin:vite:css] [postcss] Unexpected token, expected "," (9:25)
```

I am new to remix and trying to install shadcn. By default remix is working fine but when I installed shadcn UI the problem started to show. I tried to solve rewriting the tailwind.css file this way

```css
:root {
  --background: hsl(0, 0%, 100%); /* Changed to HSL for compatibility */
  --foreground: hsl(20, 14.3%, 4.1%);
  --card: hsl(0, 0%, 100%);
}
```

instead of writing this way

```css
@layer base {
     :root {
       --background: 0 0% 100%; /* This line causes the error */
       --foreground: 20 14.3% 4.1%;
       --card: 0 0% 100%;
    }
}
```

The boilerplate code is showing this problem.

### System Info

```shell
System:
    OS: Linux 6.9 Pop!_OS 22.04 LTS
    CPU: (4) x64 AMD Ryzen 3 3200G with Radeon Vega Graphics
    Memory: 3.41 GB / 13.58 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.14.0/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 9.12.2 - ~/.nvm/versions/node/v20.14.0/bin/pnpm
    bun: 1.1.13 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 130.1.71.121
```

### Used Package Manager

npm

### Expected Behavior

The CSS should compile without errors, and the styles should be applied correctly.

**Additional Information**
- I have ensured that my PostCSS and Tailwind CSS versions are up to date.
- I have tried removing the @layer directive, but I would like to use it for better organization of my styles.
- My PostCSS configuration is set up to handle Tailwind CSS.

### Actual Behavior

This error occurs when I try to compile my CSS file, which includes the @layer directive for organizing my styles.

**Actual Behaviour**
I receive the following error message:
![image](https://github.com/user-attachments/assets/3cc7ba88-f2c8-4971-af00-74b24d5c168e)
