### ISSUE TITLE
Docs issue: Can't select text of highlighted code lines

### ISSUE THREAD

**Issue by mikeybinnswebdesign** [remix-run/remix#171]
Currently the highlighting of code lines in the docs prevents text select, as the pseudo element :after is technically on top of the text in the stacking context.

You can fix it by adding this to your css:
```css
.codeblock-line[data-highlight="true"]:after {
  pointer-events: none;
}
```
