### ISSUE TITLE
Remix package doesn’t work if installed with npm ci

### ISSUE THREAD

**Issue by sergiodxa** [remix-run/remix#205]
I was trying to build Remix inside a Docker container and was following a guide where it was recommended to install packages with `npm ci` command and it failed the build because the postinstall command didn’t run.

It’s not easy to solve though, I switched to npm install.

**Comment by jaschaio** [comment]
I have the same issue. The problem seems to be caused by the [`npm ci --production` flag](https://docs.npmjs.com/cli/v8/commands/npm-install#description).

**Steps to reproduce:**

Create a new remix project:

```
npx create-remix@latest
```

Choose the defaults for everything. Enter the directory and create a `.dockerignore` and `Dockerfile`:

```.gitignore
# .dockerignore
node_modules
```

```Dockerfile
# Dockerfile
FROM node:16

COPY . .

RUN npm i --production

RUN npm run build

CMD [ "npm", "run", "start" ]
```

Run `docker build .`

You will get this error:

```
 > [3/4] RUN npm ci --production:                                                                                                                                                                           
#7 28.07                                                                                                                                                                                                    
#7 28.07 > postinstall                                                                                                                                                                                      
#7 28.07 > remix setup node                                                                                                                                                                                 
#7 28.07                                                                                                                                                                                                    
#7 28.12 sh: 1: remix: not found
#7 28.14 npm notice 
#7 28.14 npm notice New minor version of npm available! 8.3.1 -> 8.5.2
#7 28.14 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.2>
#7 28.14 npm notice Run `npm install -g npm@8.5.2` to update!
#7 28.15 npm notice 
#7 28.16 npm ERR! code 127
#7 28.16 npm ERR! path /
#7 28.17 npm ERR! command failed
#7 28.17 npm ERR! command sh -c remix setup node
```

The same happens if you change `npm ci --production` to `npm i --production`.

It works when you remove the `--production` flag.

**Comment by blasterbug** [comment]
Hello

SoI stumble upon the same error in the GitHub actions. It seems when `CI=1` then `@remix-run/server-runtime` is not installed, so impossible to build or run the app, regardless if we run `npm install` or `npm ci`. 

Which is really surprising. Right now we are trying to run our Cypress with the action `cypress-io/github-action@v2` and the build steps silently failed because of the missing package. I also tried with my own actions (see below). I am wondering if anyone else has seen this before and how they might have fixed it.

```yaml
name: Build

on:
 workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v2
      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install --unsafe-perm 
        env:
          ACCENT_COLOR: ${{ secrets.ACCENT_COLOR }}
      - name: Build artifacts
        run: npm run build
        env:
          ACCENT_COLOR: ${{ secrets.ACCENT_COLOR }}
```

The result on GitHub actions: 
![image](https://user-images.githubusercontent.com/891025/157070870-43645081-1fe0-4367-b4bc-d04760fc6ee1.png)
