### ISSUE TITLE
Tailwind.css not found in CI/CD pipeline (GitHub actions)

### ISSUE THREAD

**Issue by janhesters** [remix-run/remix#5505]
### What version of Remix are you using?

1.13

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new Remix.
2. Use Tailwind CSS with the new `unstable_tailwind: true` flag.
3. Run Playwright tests against your app in CI / CD:

```yml
name: Pull Request

on: [pull_request]

jobs:
  playwright:
    name: 🎭 Playwright
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🌐 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 🛠 Setup Database
        run: npm run prisma:wipe
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: 🎭 Playwright Run
        run: npm run test:e2e
        env:
          MAGIC_PUBLISHABLE_KEY: ${{ secrets.MAGIC_PUBLISHABLE_KEY }}
          MAGIC_SECRET_KEY: ${{ secrets.MAGIC_SECRET_KEY }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: 📸 Playwright Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
```

### Expected Behavior

It works, tests pass, app doesn't crash.

### Actual Behavior

App [crashes](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580) with:

```ts
npm run build
  shell: /usr/bin/bash -e {0}
  env:
    npm_config_cache: /home/runner/.npm

> french-house-stack@1.1.0 build
> remix build

Building Remix app in production mode...

✘ [ERROR] Could not resolve "./tailwind.css"

    app/root.tsx:28:19:
      28 │ import styles from './tailwind.css';
         ╵                    ~~~~~~~~~~~~~~~~


Build failed with 1 error:
app/root.tsx:28:19: ERROR: Could not resolve "./tailwind.css"
Error
    at Object.onCompileFailure (/home/runner/work/french-house-stack/french-house-stack/node_modules/@remix-run/dev/dist/cli/commands.js:182:1[3](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:3))
    at Object.compile (/home/runner/work/french-house-stack/french-house-stack/node_modules/@remix-run/dev/dist/compiler/remixCompiler.js:3[4](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:4):134)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:[5](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:5))
    at async Object.build (/home/runner/work/french-house-stack/french-house-stack/node_modules/@remix-run/dev/dist/compiler/build.js:33:3)
    at async Object.build (/home/runner/work/french-house-stack/french-house-stack/node_modules/@remix-run/dev/dist/cli/commands.js:177:3)
    at async Object.run (/home/runner/work/french-house-stack/french-house-stack/node_modules/@remix-run/dev/dist/cli/run.js:449:7)
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
	github.com/evanw/esbuild/internal/helpers/waitgroup.go:3[6](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:7)
main.runService.func2()
	github.com/evanw/esbuild/cmd/esbuild/service.go:12[7](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:8) +0x59
main.runService(0x1)
	github.com/evanw/esbuild/cmd/esbuild/service.go:1[8](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:9)1 +0x530
main.main()
	github.com/evanw/esbuild/cmd/esbuild/main.go:228 +0x21c

goroutine 18 [chan receive]:
main.runService.func1()
	github.com/evanw/esbuild/cmd/esbuild/service.go:111 +0x3e
created by main.runService
	github.com/evanw/esbuild/cmd/esbuild/service.go:10[9](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:10) +0x1e5

goroutine 19 [chan receive]:
main.(*serviceType).sendRequest(0xc0000a3d[10](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:11), {0x8ac3a0, 0xc003026bd0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x[11](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:12)0
main.runService.func3()
	github.com/evanw/esbuild/cmd/esbuild/service.go:138 +0x39
created by main.runService
	github.com/evanw/esbuild/cmd/esbuild/service.go:135 +0x353

goroutine 20 [chan receive]:
github.com/evanw/esbuild/internal/bundler.(*scanner).scanAllDependencies(0xc000055400)
	github.com/evanw/esbuild/internal/bundler/bundler.go:1732 +0x218
github.com/evanw/esbuild/internal/bundler.ScanBundle({_, _, _, _, _, _}, {_, _}, {0x9f44d8, 0xc000054c00}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:[12](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:13)04 +0x779
github.com/evanw/esbuild/pkg/api.rebuildImpl({0x0, 0x0, 0x0, 0xc000022570, 0x0, {0x0, 0x0}, 0x0, 0x0, {0xc000010240, ...}, ...}, ...)
	github.com/evanw/esbuild/pkg/api/api_impl.go:1143 +0x23b5
github.com/evanw/esbuild/pkg/api.buildImpl({0x0, 0x0, 0x0, 0xc000022570, 0x0, {0x0, 0x0}, 0x0, 0x0, {0xc000010240, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:864 +0x62e
github.com/evanw/esbuild/pkg/api.Build(...)
	github.com/evanw/esbuild/pkg/api/api.go:366
main.(*serviceType).handleBuildRequest(0xc0000a3d10, 0x0?, 0xc000022030?)
	github.com/evanw/esbuild/cmd/esbuild/service.go:507 +0x9c5
main.(*serviceType).handleIncomingPacket(0x0?, {0xc00013ed80?, 0x0?, 0x0?})
	github.com/evanw/esbuild/cmd/esbuild/service.go:239 +0x191
main.runService.func4()
	github.com/evanw/esbuild/cmd/esbuild/service.go:169 +0x32
created by main.runService
	github.com/evanw/esbuild/cmd/esbuild/service.go:168 +0x546

goroutine 162 [chan receive]:
main.(*serviceType).sendRequest(0xc0000a3d10, {0x8ac3a0, 0xc00033e8a0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.4({{0xc00039e280, 0x1e}, {0xc00040b8a8, 0x16}, {0x0, 0x0}, {0x0, 0x0}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:872 +0x4a6
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onLoad.func1({{0x0, 0x0}, {{0xc00039e280, 0x1e}, {0xc00040b8a8, 0x16}, {0x0, 0x0}, 0x0}})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1758 +0x19d
github.com/evanw/esbuild/internal/bundler.runOnLoadPlugins({0xc000070240?, 0x1, 0x0?}, {0x9f44d8, 0xc000054c00}, {0x9f6978, 0xc00006e220?}, 0x0?, {0xc00018cfc0, 0xc0000102a0, ...}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:925 +0xe8f
github.com/evanw/esbuild/internal/bundler.parseFile({{0x9f6978, 0xc00006e220}, {0xc00018cfc0, 0xc0000102a0, 0xc0000102b8, 0xc00006e1e0, 0x6, 0xc000022c30}, {0x9f44d8, 0xc000054c00}, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:129 +0x246
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:[13](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:14)[28](https://github.com/janhesters/french-house-stack/actions/runs/4207143214/jobs/7301561580#step:7:29) +0x9b7
```
