### ISSUE TITLE
"@namespace" rules are not supported

### ISSUE THREAD

**Issue by tavoyne** [remix-run/remix#6444]
### What version of Remix are you using?

1.16.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [x] Yes

### Steps to Reproduce

Import a CSS file that contains `@namespace svg "http://www.w3.org/2000/svg";`.

Don't use any of the new CSS integrations, just a plain old CSS import.

### Expected Behavior

No warning.

### Actual Behavior

The warning:

```
"@namespace" rules are not supported [unsupported-@namespace]
```

is shown in the console.

**Comment by markdalgleish** [comment]
This warning is coming from esbuild, not something we have control over.

Warnings aside, is the built CSS correct? In my local testing against esbuild directly, despite warning me that `@namespace` rules aren't supported, the following input generates the following output:

Input CSS:

```css
@namespace svg url('http://www.w3.org/2000/svg');

a {
  color: orangered;
}

svg|a {
  fill: blueviolet;
}
```

Output:

```css
@namespace svg url(http://www.w3.org/2000/svg);a{color:#ff4500}svg|a{fill:#8a2be2}
```

If this is causing you issues, I'd raise an issue upstream against esbuild.
