### ISSUE TITLE
`@remix-run/web-fetch` tries to access `@remix-run/web-blob`, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by lensbart** [remix-run/remix#7434]
### What version of Remix are you using?

2.0.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

* Use Yarn PnP (zero-installs)
* Use Remix

## Workaround

Add the following to your `yarnrc.yml`:
```yml
# yarnrc.yml

packageExtensions:
  # awaiting fix: https://github.com/remix-run/remix/issues/7434
  '@remix-run/web-fetch@*':
    dependencies:
      '@remix-run/web-blob': '*'
```
and run `yarn` again

See also [this request](https://github.com/remix-run/remix/discussions/7169) which would help avoiding these issues in the future

### Expected Behavior

No error

### Actual Behavior

> Error: @remix-run/web-fetch tried to access @remix-run/web-blob, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

### How to fix

Update the dependencies in the `package.json` of `@remix-run/web-fetch` to include `@remix-run/web-blob`
