### ISSUE TITLE
Environment variables not available in AWS ECS instance.

### ISSUE THREAD

**Issue by unclejustin** [remix-run/remix#9049]
### Reproduction

You need AWS to reproduce. So best I can do is outline the steps.

1. Create an ECS service.
2. Set any environment variable
3. ssh into server and confirm that env var is available
4. log env var in a loader function (see below)
5. Check server logs and notice that env var is not available

Process.env will only ever have the default environment variables provided by node.

I was able to get around this by using a custom express server and adding process.env to the context like this:

```js
app.all(
  "*",
  createRequestHandler({
    build,
    getLoadContext() {
      // eslint-disable-next-line no-undef
      return { env: process.env };
    },
  }),
);
```

Now if I look at context inside of a loader function the context is populated but process.env is not.

```ts
export const loader = ({ context }: LoaderFunctionArgs) => {
  // context will have the env vars loaded
  console.log("🚀 ~ loader ~ context:", context);

  // process.env will not
  console.log("🚀 ~ loader ~ process.env", process.env);

  const GOOGLE_CALLBACK_URL = getEnvVar("GOOGLE_CALLBACK_URL");
  const DATABASE_URL = getEnvVar("DATABASE_URL");

  return json({ GOOGLE_CALLBACK_URL, DATABASE_URL });
};
```

### System Info

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC 7R13 Processor
    Memory: 6.88 GB / 7.57 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
  npmPackages:
    @remix-run/express: ^2.8.1 => 2.8.1 
    @remix-run/node: ^2.8.0 => 2.8.1 
    @remix-run/react: ^2.8.0 => 2.8.1 
    @remix-run/serve: ^2.8.0 => 2.8.1 
    @remix-run/server-runtime: ^2.8.0 => 2.8.1
```

### Used Package Manager

npm

### Expected Behavior

`process.env.VARIABLE_NAME` should be available.

### Actual Behavior

`process.env.VARIABLE_NAME` is undefined.

**Comment by brophdawg11** [comment]
How are you setting the environment variable?  I'm not too familiar with AWS but I found https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html and https://docs.aws.amazon.com/AmazonECS/latest/developerguide/use-environment-file.html on a quick search - are you doing either of those to set the value?

**Comment by unclejustin** [comment]
Thanks for the reply @brophdawg11 ! I am setting the env vars in the task definition like it shows in the first link.

The strangest thing to me is that the envars are available in ssh and in context. Almost like node is "waiting" for them.

I am not confident this is "Remix" problem either, but a node problem. Currently I am working on generating a .env file during the container build and referencing that, which seems to be working so far. I'll report back once I have  a workaround.

**Comment by unclejustin** [comment]
Just in case anyone stumbles on this in the future, here's my workaround.

In my github action where I'm building the docker container I inline all of the build args like this:

```yaml
- name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build --progress=plain -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --build-arg GOOGLE_CALLBACK_URL=${{ env.GOOGLE_CALLBACK_URL }} \
            .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "imageid=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
```

The important bit is the `--build-arg`. Then in the Dockerfile

```docker
ARG GOOGLE_CALLBACK_URL
ENV GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
```

Now GOOGLE_CALLBACK_URL will be available in the app.
